(function() {var implementors = {
"air":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"air/trace/stats/log_data/struct.LogKey.html\" title=\"struct air::trace::stats::log_data::LogKey\">LogKey</a>"]],
"air_interpreter_cid":[["impl&lt;Val&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"air_interpreter_cid/struct.CID.html\" title=\"struct air_interpreter_cid::CID\">CID</a>&lt;Val&gt;"]],
"air_interpreter_data":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"air_interpreter_data/struct.GenerationIdx.html\" title=\"struct air_interpreter_data::GenerationIdx\">GenerationIdx</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"air_interpreter_data/struct.TracePos.html\" title=\"struct air_interpreter_data::TracePos\">TracePos</a>"]],
"air_interpreter_interface":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"air_interpreter_interface/struct.SerializedCallArguments.html\" title=\"struct air_interpreter_interface::SerializedCallArguments\">SerializedCallArguments</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"air_interpreter_interface/struct.SerializedCallRequests.html\" title=\"struct air_interpreter_interface::SerializedCallRequests\">SerializedCallRequests</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"air_interpreter_interface/struct.SerializedCallResults.html\" title=\"struct air_interpreter_interface::SerializedCallResults\">SerializedCallResults</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"air_interpreter_interface/struct.SerializedTetraplets.html\" title=\"struct air_interpreter_interface::SerializedTetraplets\">SerializedTetraplets</a>"]],
"air_interpreter_signatures":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"air_interpreter_signatures/struct.ArchivedPublicKey.html\" title=\"struct air_interpreter_signatures::ArchivedPublicKey\">ArchivedPublicKey</a><div class=\"where\">where\n    <a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/alloc/boxed/struct.Box.html\" title=\"struct alloc::boxed::Box\">Box</a>&lt;[<a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.u8.html\">u8</a>]&gt;: Archive,</div>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"air_interpreter_signatures/struct.PublicKey.html\" title=\"struct air_interpreter_signatures::PublicKey\">PublicKey</a>"]],
"air_parser":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"air_parser/ast/struct.Span.html\" title=\"struct air_parser::ast::Span\">Span</a>"],["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"air_parser/struct.AirPos.html\" title=\"struct air_parser::AirPos\">AirPos</a>"]],
"air_test_framework":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"air_test_framework/ephemeral/struct.PeerId.html\" title=\"struct air_test_framework::ephemeral::PeerId\">PeerId</a>"]],
"polyplets":[["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/hash/trait.Hash.html\" title=\"trait core::hash::Hash\">Hash</a> for <a class=\"struct\" href=\"polyplets/struct.ResolvedTriplet.html\" title=\"struct polyplets::ResolvedTriplet\">ResolvedTriplet</a>"]]
};if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()